#!/bin/sh

identify -format "%[fx:w]px × %[fx:h]px" "$2" > /tmp/$$-old
identify -format "%[fx:w]px × %[fx:h]px" "$1" > /tmp/$$-new

cmp --silent /tmp/$$-old /tmp/$$-new
if [ $? -ne 0 ]; then
    echo -ne "Resize: $1\n    "
    cat /tmp/$$-old
    echo -n " -> "
    cat /tmp/$$-new
else
    if cat /tmp/$$-old | gawk 'match($0, /(.*)px × (.*)px/, cap) {exit (cap[1] > cap[2]);}'; then
        format="3x1"
    else
        format="1x3"
    fi
    compare "$2" "$1" png:- | montage -tile $format -geometry +4+4 "$2" - "$1" png:- > /tmp/diff.png && eog /tmp/diff.png > /dev/null 2>&1
fi

rm /tmp/$$-old
rm /tmp/$$-new
