#!/bin/sh

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Starts gnome-keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK

exec nm-applet &

exec numlockx on &
# the sleep is a ugly hack to ensure xmodmap runs after awesome sets xkb stuffs
exec {sleep 10s && xmodmap /home/martin/.config/Xmodmap && xcape -e "Hyper_L=space"} &
exec xbindkeys &

exec /home/martin/.config/awesome/wallpaper &

exec awesome
