" for bundle, various plugins
    set nocompatible       " be iMproved
    filetype off           " required!

    let g:HasVundle = !empty(glob(expand("~") . "/.vim/bundle/vundle/*"))
    if g:HasVundle
        set runtimepath+=~/.vim/bundle/vundle
        call vundle#begin()

        Plugin 'LanguageTool'
        Plugin 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
        Plugin 'SirVer/ultisnips'
        Plugin 'Valloric/YouCompleteMe'
        Plugin 'ervandew/supertab'
        Plugin 'gmarik/vundle'
        Plugin 'javacomplete'
        Plugin 'pbrisbin/vim-mkdir'
        Plugin 'scrooloose/syntastic'
        Plugin 'terryma/vim-expand-region'
        Plugin 'tpope/vim-commentary'
        Plugin 'tpope/vim-endwise'
        Plugin 'tpope/vim-eunuch'
        Plugin 'tpope/vim-liquid'
        Plugin 'tpope/vim-sensible'
        Plugin 'yegappan/mru'

        call vundle#end()
    end

" Set <leader> key to a more azerty-friendly key (must appear before any
" mapping using it)
    let mapleader = ","

" For syntastic
    " deactivate lacheck as it is most often annoying, usually redundant with
    " chktex and has no per-check deactivation option
    let g:syntastic_tex_checkers = ['chktek']

" terryma/vim-expand-region default mapping for shrink is _
    map - <Plug>(expand_region_shrink)

" for ultisnips
    " If you want :UltiSnipsEdit to split your window.
    let g:UltiSnipsEditSplit="horizontal"

    " For ultisnips & ycm compatibility
    let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
    let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
    let g:SuperTabDefaultCompletionType = '<C-n>'

" for C++
    let g:ycm_global_ycm_extra_conf = '~/.vim/bundle/YouCompleteMe/cpp/ycm_extra_conf.py'
    let g:syntastic_cpp_compiler_options='-std=c++1y'
    let g:ycm_complete_in_comments=1
    let g:ycm_confirm_extra_conf=0
    set matchpairs+=<:>
    " disable autocomment for //
    au FileType c,cpp setlocal comments-=:// comments+=f://
    autocmd BufNewFile,BufRead *.tpp set filetype=cpp
    autocmd BufNewFile,BufRead /usr/include/c++/* set filetype=cpp

    set path+=include

" for java
    autocmd Filetype java setlocal omnifunc=javacomplete#Complete
    set suffixes+=.class

    let g:syntastic_java_javac_config_file_enabled=1

" for html and css
    autocmd Filetype htlm,css set sw=2

" spell checking and wrapping in some file types
    autocmd Filetype gitcommit set spell textwidth=72 nofoldenable colorcolumn=51,73
    autocmd Filetype mkd,liquid,tex set spell textwidth=80

" egg
    autocmd BufNewFile,BufRead *.egg set filetype=egg

" llvm ir code
    autocmd BufNewFile,BufRead *.ll set filetype=llvm

" latex
    autocmd BufNewFile,BufRead *.tex set suffixes+=*.aux,*.pdf,*.fdb_latexmk,*.fls,*.log,*.out,*.toc sw=2

" evolution
    autocmd BufRead /tmp/evo* set spell filetype=mail colorcolumn=72

" Flag problematic whitespace (trailing spaces, spaces before tabs).
highlight BadWhitespace term=standout ctermbg=red guibg=red
match BadWhitespace /\s\+$\| \+\t/

" Don't exit visual mode when shifting.
vnoremap < <gv
vnoremap > >gv

" Move up and down by visual lines not buffer lines.
nnoremap <Up>   gk
vnoremap <Up>   gk
nnoremap <Down> gj
vnoremap <Down> gj

" toggle line numbers
nnoremap <silent><Leader>n :set relativenumber!<CR>

" toggle spell lang
function! ToggleSpell()
    if &spell == 0
        set spell
        set spelllang=en
        echo 'spelllang=en'
    elseif &spelllang =~# 'en'
        set spell
        set spelllang=fr
        echo 'spelllang=fr'
    elseif &spelllang =~# 'fr'
        set nospell
        echo 'nospell'
    endif
endfunction

noremap <leader>z <ESC>:call ToggleSpell()<CR>

" other stuffs
    filetype plugin indent on
    set cpoptions+="#"
    set expandtab
    set foldmethod=marker
    set gdefault                    " makes :s///g default
    set guioptions-=lLrRT
    set list
    set listchars=nbsp:¬,tab:→ 
    set mouse=a
    set number
    set shiftwidth=4
    set showcmd                     " show partial commands
    syntax on

    " set split bar to be contiguous (there is an unbreakable space at the end
    " of that line — vim does not like classic space here)
    set fillchars=vert: 

    " color at 80th column
    set colorcolumn=81,91,101
    hi ColorColumn ctermbg=lightgrey

    " close quick fix list on selection
    autocmd FileType qf nmap <buffer> <cr> <cr>:ccl<cr>

    nnoremap <leader>m :!make<cr>
    nnoremap <leader>w <c-w>

